WebApp/QuestpondTrainingWebApp/Models/ErrorViewModel.cs
namespace QuestpondTrainingWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/QuestpondTrainingWebApp/Models/ProductViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace QuestpondTrainingWebApp.Models
{
    public class ProductViewModel
    {
        [ScaffoldColumn(false)]
        [DisplayName("Product ID")]
        [Required(ErrorMessage = "Product ID is mandatory")]
        public int ProductId { get; set; }

        [DisplayName("Product Name")]
        [Required(ErrorMessage ="Product Name is mandatory")]
        [RegularExpression("^[a-zA-Z0-9 ]+$", ErrorMessage ="Product Name can contain alphabets, digits and space")]
        public string ProductName { get; set; }

        [DisplayName("Product Code")]
        [Required(ErrorMessage = "Product Code is mandatory")]
        public string ProductCode { get; set; }

        [DisplayName("Product Price")]
        [Range(0, double.MaxValue)]
        [Required(ErrorMessage = "Product Price is mandatory")]
        public decimal ProductPrice { get; set; }
    }
}

WebApp/QuestpondTrainingWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using QuestpondTrainingWebApp.Models;
using System.Diagnostics;

namespace QuestpondTrainingWebApp.Controllers
{
    // will be accessed from outside
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/QuestpondTrainingWebApp/Controllers/ProductController.cs
using BusinessLogic.Abstraction;
using BusinessLogic.Implementation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using QuestpondTrainingWebApp.Models;
using ViewModels;

namespace QuestpondTrainingWebApp.Controllers
{
    public class ProductController : Controller
    {
        static List<ProductViewModel> products = new List<ProductViewModel> { new ProductViewModel() { ProductId = 001, ProductCode = "P001", ProductName = "Laptop", ProductPrice = 50000 } };
        private readonly IProductBL _productBL;
        private readonly ICategoryBL _categoryBL;

        public ProductController(IProductBL productBL, ICategoryBL categoryBL)
        {
            _productBL = productBL;
            _categoryBL = categoryBL;
        }

        public IActionResult GetProductInfo(int productId)
        {
            ProductViewModel productViewModel = new ProductViewModel
            {
                ProductPrice = 123,
                ProductCode = "P001",
                ProductId = 1,
                ProductName = "Product 1"
            };

            //  ViewData["product"] = productViewModel;
            return View("Index", productViewModel);

        }

        [Route("product/create")]
        //[HttpPost]
        public IActionResult CreateProduct()
        {
            var categories = new SelectList(_categoryBL.GetActiveCategories(), "CategoryId", "CategoryName");
            ViewBag.Categories = categories;
            return View();
        }

        [Route("product/addproduct")]
        public IActionResult SaveProduct(ProductViewModel productViewModel, int view = 0)
        {
            //check duplicate product validation
           if(!string.IsNullOrEmpty(productViewModel.ProductName) && DuplicateProduct(productViewModel.ProductName, productViewModel.ProductId)) {
                ModelState.AddModelError("DuplicateCheck", "Product Name already exists");
            }

            if (ModelState.IsValid)
            {
                if(productViewModel.ProductId > 0)
                {
                    _productBL.UpdateProduct(productViewModel);
                }
                else
                    _productBL.AddProduct(productViewModel);
                return RedirectToAction("Summary", "Product");
               
            }

            var categories = new SelectList(_categoryBL.GetActiveCategories(), "CategoryId", "CategoryName");
            ViewBag.Categories = categories;
            return View("CreateProduct");
        }

        [HttpGet]
        [Route("product/product-list")]
        public IActionResult Summary(int view = 0)
        {
            var products = _productBL.GetAllProducts();
            if (view == 0)
            {
                return View("SaveProduct", products);
            }
            else
            {
                return View("productcards", products);
            }

        }

        [HttpGet] // as this is link, so it will redirect and make a direct request. For put, delete, we need to make post call using ajax
        [Route("delete/{productid}")]
        public IActionResult DeleteProduct(int productid)
        {
            var isDeleted = _productBL.DeleteProduct(productid);
            return RedirectToAction("Summary", "Product");
        }

        [HttpGet]
        [Route("edit/{productid}")]
        public IActionResult EditProduct(int productid)
        {
            var product = _productBL.GetProductById(productid);
            var categories = new SelectList(_categoryBL.GetActiveCategories(), "CategoryId", "CategoryName");
            ViewBag.Categories = categories;

            return View("EditProduct", product);
        }

        private bool DuplicateProduct(string productName, int productId)
        {
            return _productBL.DuplicateCheck(productName, productId);
        }
    }
}

WebApp/QuestpondTrainingWebApp/Custom/DiscountOffersViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace QuestpondTrainingWebApp.Component
{
    public class DiscountOffersViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(decimal price)
        {
            if (price > 50000)
            {
                decimal discount = price * 15 / 100;
                decimal finalprice = price - discount;
                return View("_discountOffer", finalprice);
            }           

            return View("_noOffer");
        }
    }
}

WebApp/QuestpondTrainingWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core. We are creating Product app</a>.</p>

</div>

WebApp/QuestpondTrainingWebApp/Views/Product/CreateProduct.cshtml
@model ProductViewModel
@{
    ViewData["Title"] = "CreateProduct";
}

<h1>Create New Product</h1>

@* <form method="post" action="/product/addproduct">
    <div>
        <label name="ProductId">Product ID</label>
        <input type="text" name="ProductId" />
    </div>
     <div>
        <label name="ProductCode">Product Code</label>
        <input type="text" name="ProductCode" />
    </div>
     <div>
        <label name="ProductName">Product Name</label>
        <input type="text" name="ProductName" />
    </div>
     <div>
        <label name="ProductPrice">Product Price</label>
        <input type="text" name="ProductPrice" />
    </div>
    <input type="submit" name="saveProduct" value="Save Product"/>
</form> *@

@* @using (Html.BeginForm("addproduct", "product", FormMethod.Post))
{
    <form method="post" action="/product/addproduct">
        <div class="row">
            <div class="mb-3">
                @Html.LabelFor(m => m.ProductId, new { @class = "form-label" })
                @Html.TextBoxFor(m => m.ProductId, new { @class = "form-control" })
            </div>
            <div class="mb-3">
                @Html.LabelFor(m => m.ProductCode, new { @class = "form-label" })
                @Html.TextBoxFor(m => m.ProductCode, new { @class = "form-control" })
            </div>
            <div class="mb-3 ">
                @Html.LabelFor(m => m.ProductName, new { @class = "form-label" })
                @Html.TextBoxFor(m => m.ProductName, new { @class = "form-control" })
            </div>
            <div class="mb-3">
                @Html.LabelFor(m => m.ProductPrice, new { @class = "form-label" })
                @Html.TextBoxFor(m => m.ProductPrice, new { @class = "form-control" })
            </div>
            <div class="container flex-container">
                <button type="submit" class="btn btn-primary" name="saveProduct">Save Product</button>
            </div>
            <div>

            </div>
        </div>
    </form>
 } *@

<div class="row">
    <div class="col-lg-6 col-sm-9">
        <form method="post" asp-action="addproduct" asp-controller="product">
            <div asp-validation-summary="All" class="text-danger"></div>
            @* <div class="form-group"> *@
            @*     <label asp-for="ProductId"></label> *@
            @*     <input type="text" asp-for="ProductId" class="form-control" disabled/> *@
            @*     <span asp-validation-for="ProductId" class="text-danger"></span> *@
            @* </div> *@
            <div class="form-group"> 
                <label asp-for="CategoryId"></label>    
                <select class="form-select" asp-items="ViewBag.Categories" asp-for="CategoryId">
                    <option valaue="">---Select---</option>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </select>

            </div>
            <div class="form-group">
                <label asp-for="ProductCode"></label>
                <input type="text" asp-for="ProductCode" class="form-control" />
                <span asp-validation-for="ProductCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductName"></label>
                <input type="text" asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice"></label>
                <input type="text" asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="container flex-container">
                <input type="submit" class="btn btn-primary" value="Save Product" />
            </div>       
        </form>

        <example-custom author="Sumedha Jhanji"></example-custom>

        <partial name="_ValidationScriptsPartial" />
    </div>
</div>

WebApp/QuestpondTrainingWebApp/Views/Product/EditProduct.cshtml
@model ProductViewModel
@{
    ViewData["Title"] = "CreateProduct";
}

<h1>Edit Product</h1>


<div class="row">
    <div class="col-lg-6 col-sm-9">
        <form method="post" asp-action="addproduct" asp-controller="product">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group"> 
                <input type="hidden" asp-for="ProductId"/>
                <label asp-for="CategoryId"></label>    
                <select class="form-select" asp-items="ViewBag.Categories" asp-for="CategoryId">
                    <option valaue="">---Select---</option>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </select>

            </div>
            <div class="form-group">
                <label asp-for="ProductCode"></label>
                <input type="text" asp-for="ProductCode" class="form-control" />
                <span asp-validation-for="ProductCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductName"></label>
                <input type="text" asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice"></label>
                <input type="text" asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="container flex-container">
                <input type="submit" class="btn btn-primary" value="Edit Product" />
            </div>       
        </form>

        <partial name="_ValidationScriptsPartial" />
    </div>
</div>

WebApp/QuestpondTrainingWebApp/Views/Product/Index.cshtml
@*
@{
    ViewData["Title"] = "GetProductInfo";
}

<h1>GetProductInfo</h1>
<h4>This is my product</h4>
@{
    ProductViewModel product = ViewData["product"] as ProductViewModel;
}
<p>Product Details</p>
<p>Product Id: @product.ProductId</p>
<p>Product Name: @product.ProductName</p>
<p>Product Code: @product.ProductCode</p>
<p>Product Price: @product.ProductPrice</p>

 *@

@model ProductViewModel
@{
    ViewData["Title"] = "GetProductInfo";
}

<div class="text-center">
    <h1 class="display-4">Product Details</h1>
    <p>Product Id: @Model.ProductId</p>
    <p>Product Name: @Model.ProductName</p>
    <p>Product Code: @Model.ProductCode</p>
    <p>Product Price: @Model.ProductPrice</p>

</div>

WebApp/QuestpondTrainingWebApp/Views/Product/ProductCards.cshtml
@model List<ProductViewModel>
@{
    ViewData["Title"] = "ProductCards";
}
<div class="row">

@foreach (var item in Model)
{
    @Html.Partial("_productCard", item)
}
</div>


<div class="container flex-container">
    <a class="btn btn-primary" href="/product/create">Create New Product</a>
</div>

WebApp/QuestpondTrainingWebApp/Views/Product/SaveProduct.cshtml
@model List<ProductViewModel>
@{
    ViewData["Title"] = "SaveProduct";
}

<h1>Products List</h1>

<table class="table table-light">
    <thead>
        <tr>
            <td>Product ID</td>
            <td>Product Code</td>
            <td>Product Name</td>
            <td>Product Price</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.ProductId</td>
                <td>@product.ProductCode</td>
                <td>@product.ProductName</td>
                <td>@product.ProductPrice</td>
                <td>
                    <a asp-action="EditProduct" title="Edit Product" asp-controller="Product" asp-route-productid="@product.ProductId"
                       class="btn btn-warning" >Edit</a>
                </td>
                <td>
                    <a asp-action="DeleteProduct" title="Delete Product" asp-controller="Product" asp-route-productid="@product.ProductId"
                       class="btn btn-danger" onclick="return confirm('Do you really wany to delete the product');">X</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<generate-ordered-list>
    @if (Model.Count > 1)
    {
        @String.Join(",", Model.Select(p => p.ProductName));
    }
</generate-ordered-list>

<div class="container flex-container">
    <a class="btn btn-primary" href="/product/create">Create New Product</a>
</div>

WebApp/QuestpondTrainingWebApp/Views/Shared/Components/DiscountOffers/_discountOffer.cshtml
@model decimal

<div class="alert alert-success">
    <strong>Discount Offer price: @Model</strong>
</div>

WebApp/QuestpondTrainingWebApp/Views/Shared/Components/DiscountOffers/_noOffer.cshtml
<div class="alert alert-warning">
    <strong>No offer for this product</strong>
</div>

WebApp/QuestpondTrainingWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QuestpondTrainingWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QuestpondTrainingWebApp.styles.css" asp-append-version="true" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <style>
        .flex-container {
            display: flex;
            justify-content: flex-end;
            align-items: flex-end;
            height: 200px;
        }
    </style>
</head>
<body>
    <header>
       @*  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QuestpondTrainingWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
        @Html.Partial("_navbar", "")
    </header>
    <div class="container">
        
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - QuestpondTrainingWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/QuestpondTrainingWebApp/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">QuestpondTrainingWebApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/product/create">Add Product</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/product/product-list">Product List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/product/product-list?view=1">Product list (Cards)</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

WebApp/QuestpondTrainingWebApp/Views/Shared/_productcard.cshtml
@model ProductViewModel

<div class="card " style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.ProductName</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">@Model.ProductCode</h6>
        <h6 class="card-subtitle mb-2 text-body-secondary">Price: <b>INR</b> @Model.ProductPrice</h6>
        <vc:discount-offers price="@Model.ProductPrice"></vc:discount-offers>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-secondary">View Details</a>
    </div>
</div>